from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from zipfile import ZipFile
import json
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "src" / "data" / "generated-documents.ts"
NS = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"


@dataclass(frozen=True)
class DocumentSource:
    key: str
    path: Path


SOURCES = (
    DocumentSource(
        "jikeCompanyIntro",
        ROOT / "source-materials" / "jike" / "公司LOGO与简介" / "深圳市积科科技有限公司简介.docx",
    ),
    DocumentSource(
        "jikeJk100",
        ROOT / "source-materials" / "jike" / "产品列表" / "PVC热稳定稳定剂" / "JK-100环保稳定剂.docx",
    ),
    DocumentSource(
        "jikeAos10",
        ROOT / "source-materials" / "jike" / "产品列表" / "CPVC热稳定剂" / "AOS-10 有机稳定剂（CPVC专用）.docx",
    ),
    DocumentSource(
        "jikeTheic",
        ROOT / "source-materials" / "jike" / "产品列表" / "功能助剂" / "赛克.docx",
    ),
    DocumentSource(
        "alphaCompanyIntro",
        ROOT / "source-materials" / "alpha" / "公司名称及LOGO" / "公司简介.docx",
    ),
    DocumentSource(
        "alphaDh273",
        ROOT / "source-materials" / "alpha" / "产品列表" / "DH-273锌烧抑制剂.docx",
    ),
    DocumentSource(
        "alphaAef18",
        ROOT / "source-materials" / "alpha" / "产品列表" / "PVC加工稳定助剂 AEF-18.docx",
    ),
    DocumentSource(
        "alphaCcl601",
        ROOT / "source-materials" / "alpha" / "产品列表" / "电阻率稳定剂CCL-601.docx",
    ),
    DocumentSource(
        "alphaAft180",
        ROOT / "source-materials" / "alpha" / "产品列表" / "粉体防团聚剂 AFT-180.docx",
    ),
    DocumentSource(
        "alphaTheic",
        ROOT / "source-materials" / "alpha" / "产品列表" / "赛克.docx",
    ),
    DocumentSource(
        "alphaAef477",
        ROOT / "source-materials" / "alpha" / "产品列表" / "高效辅助热稳定剂AEF-477TDS.docx",
    ),
)


def main() -> None:
    documents = {source.key: extract_blocks(source.path) for source in SOURCES}
    OUTPUT_PATH.write_text(render_typescript(documents), encoding="utf-8")


def extract_blocks(path: Path) -> list[dict[str, object]]:
    with ZipFile(path) as archive:
        xml = archive.read("word/document.xml")

    tree = ET.fromstring(xml)
    body = tree.find("w:body", NS)
    if body is None:
        return []

    blocks: list[dict[str, object]] = []
    for child in list(body):
        if child.tag == W + "p":
            text = text_from(child)
            if text:
                blocks.append({"type": "paragraph", "text": text})
        elif child.tag == W + "tbl":
            rows = table_rows(child)
            if rows:
                blocks.append({"type": "table", "rows": rows})

    return blocks


def table_rows(table: ET.Element) -> list[list[str]]:
    rows: list[list[str]] = []
    for row in table.findall("w:tr", NS):
        cells = [cell_text(cell) for cell in row.findall("w:tc", NS)]
        if any(cells):
            rows.append(cells)
    return rows


def cell_text(cell: ET.Element) -> str:
    paragraphs = [text_from(p) for p in cell.findall(".//w:p", NS)]
    return "\n".join(text for text in paragraphs if text)


def text_from(element: ET.Element) -> str:
    return "".join(text.text or "" for text in element.findall(".//w:t", NS)).strip()


def render_typescript(documents: dict[str, list[dict[str, object]]]) -> str:
    data = json.dumps(documents, ensure_ascii=False, separators=(",", ":"))
    return (
        "import type { DocumentBlock } from './types'\n\n"
        "// Generated from source-materials/*.docx by scripts/extract-word-documents.py.\n"
        "// Do not edit this file by hand; update the Word files and regenerate it.\n"
        f"export const wordDocuments = {data} as const satisfies Record<string, readonly DocumentBlock[]>\n"
    )


if __name__ == "__main__":
    main()
